### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by hardevik** [BevoTechPack/BevoTechPack#1005]
My induction Smelter don't let me put Stuff in the first  slot only the second one bug? http://puu.sh/pquS6/f9ba1f9cb5.png

**Comment by b0bst3r** [comment]
Most likely the flux slot lock is on, that grey box with nothing in should contain something, if you're using a resourcepack remove it and look again.  Since you failed to tell me again what version of the pack you're playing I can't tell you if you should update or not.  Either way this is not a bug
