### ISSUE TITLE
BuildCraft addons

### ISSUE THREAD

**Issue by Loplopp21** [BevoTechPack/BevoTechPack#1059]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug
Ive put some Adons from Buildcraft into the modpack but this appeared:
https://cloud.githubusercontent.com/assets/20892711/17488187/700cb946-5d98-11e6-9df0-f4bb4d9b2c55.PNG
Did I need some other coremods?

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - BuildCraft Addons
Do you use optifine? -Yes
Did the problem appear in single player or on a server? - 
SinglePlayer

**Comment by bookerthegeek** [comment]
You installed the buildcraft jar along withe the seperate core files. Delete buildcraft jar

**Comment by Loplopp21** [comment]
When I delete the buildcraft jar, the game just crash...

**Comment by b0bst3r** [comment]
You can either install all the separate Buildcraft modules which gives you choices to NOT include some or you can put in the Buildcratf jar files which is ALL of the separate modules combined into 1 mod.  You cannot have both, if you read the actual line of text in your screen shot it says and I quote:

"You have mod sources that are DUPLICATE within your system" and even lists them, just put it back how it was you have all those already.

**Comment by Loplopp21** [comment]
Its caus, I cant craft the quarry/mashine base, and i ment the recipe is in the addons
How can I put the recipe in my client?

**Comment by b0bst3r** [comment]
From the BTPR FAQ 

Q - I've been asked on numerous occasions about the Buildcraft Quarry and how to re-enable it, there are so many better less world destructive quarry type machines in this pack from Mekanism's Digital Miner to Magneticraft's Miner to Extra Utilities's Ender Quarry that there are so many better choices. But I still get asked after pointing all those out so, how do you enable the Buildcraft Quarry?

A - Delete minecraft\scripts\bc6.zs, in game do a /mt reload (you will have to start a LAN game and enable cheats if you're playing SSP and the server needs to do this if playing SMP). The Buildcraft Quarry is called Machine Block though due to a clash of block names with NuclearCraft.
