### ISSUE TITLE
Spawner fail

### ISSUE THREAD

**Issue by errorjar** [BevoTechPack/BevoTechPack#1101]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- Bevo R hotfix

###Mc crash

### http://pastebin.com/cMBhyY5C

Questions:

Did you add any additional mods? - OpenComputers,dimensional-anchor-59.0.2,portel-gun,Custom-NPC,Boims 0`Planti
Do you use optifine? -no
Did the problem appear in single player or on a server? - on server

**Comment by b0bst3r** [comment]
Remove Fastcraft and see what's going on with the spawner.

**Comment by errorjar** [comment]
i habe disabel dirt monster this was the bug

**Comment by b0bst3r** [comment]
Oh yeah that bug, you can't disable EnderZoo's Dirt Slime on the server and not change all the client configs.  If you do change just the server it causes all sorts of crashes, this is by design and not something I can fix.  To fix re-enable the dirt slimes and change the rarity of them to 0 which stops them from spawning.
