### ISSUE TITLE
Botainia causes strange, frustrating problems.

### ISSUE THREAD

**Issue by mSt3in** [BevoTechPack/BevoTechPack#838]
This mod has been fingered as causing a lot of problems in our server.

Bevo; please put the warp book recp back to default.

Break a manapool with a silktouch tool.  Did it hose the server? try again.  It will.  try again. It will bomb your server.  Playing single? go away.  SMP?  this original, interesting yet problomatic mod is your problem.

I am so happy I found the problem!  Botainia, die!!!!  Laugh/cry, I found it! I found the problem!!!!  I can repro...ha ha ha ha ha.

**Comment by ace13** [comment]
You know, manical laughter in bug reports feels a bit... creepy.

You're not planning on becoming an evil overlord / project manager in the future I hope?

**Comment by mst3in** [comment]
Let's say you have a server you love, that suddenly turns to shit (but doesn't fully crash so there isn't really any log to go by) and you have to restore backups to get it to work right again...then after a time thisd issue happens again.  Players point fingers and don't know but we restore and move on.  You start loosing your mind a little trying to find out why because logs are no help.  Then, one inebriated evening, you repro the cause yourself.  Bamn!   Magic!  Moment of clarity!  You too, would experiance an overwhelming urge to crap all over the githubs.

I need to set up a new server where I can repro this issue by itself, tracking it here:

https://github.com/Vazkii/Botania/issues/644

**Comment by ace13** [comment]
I've found that the Java VisualVM is really good for debugging issues where the server doesn't fully crash, you can connect your debugger remotely onto the servers java process and get all the debugging data you need without needing crash logs to go through.

In my case, for a server running on another machine, I just set a port for jmxremote and run it without authentication inside the local network;
```
-Dcom.sun.management.jmxremote.port=4567
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.authenticate=false
```

I guess it's not of much help now though, since you seem to have already found a way to reproduce the issue.

**Comment by mst3in** [comment]
Thank's ace that's good info.

**Comment by mst3in** [comment]
I dumped some time on a new server to repro.

Adding to the frustration is that on my new test server I can't repro this:

"...if you break livingwood/livingrock with a TC hammer, only the targeted living-block is broken as a living block. The adjacent living blocks break as oak/stone. If you use a lumber axe, you get the same behavior."

I have no idea how to even begin troubleshooting that.  The client might be assuming things that haven't actually happened on the server.  Maybe there is some crazy mod interactions.  (I did mention that the main server has a ton of stuff going on right? glactic, big-r, thuam like crazy, and of course ae2 everywhere...)
