### ISSUE TITLE
Tinkers Tools issue

### ISSUE THREAD

**Issue by xhiyikfkox** [BevoTechPack/BevoTechPack#926]
Some of the tinkers tools are uncraftable as well as their parts, one for instance is making tools and parts from unstable ingots yet the parts show in nei just smeltery is unable to pour the casts. Possible fix is consider adding in Extra TiC as it adds in more parts for tools and weapons such as enderium tool parts and weapons, metals already existant in the pack and may fix the ones showing up but not working like the unstable tools.

**Comment by Watschman** [comment]
I belief Extra Utilities Unstable tools are bugged out in general but I have to decompile the source code of extra Utilities to confirm that because it's closed source. But I can take a look if I find the right handler in the source code. ExtraTiC would be cool but I thought b0bst3r had decided against this mod.

**Comment by b0bst3r** [comment]
Fixed in Release 1.0 :)
