### ISSUE TITLE
Right-click ceases to work after pausing game for a bit

### ISSUE THREAD

**Issue by otakucode** [BevoTechPack/BevoTechPack#960]
In Survival Single Player, if I pause the game by hitting Esc, then leave it that way for several minutes, then come back to the game, upon continuing, right-click no longer works.  Chests cannot be opened, furnaces can not be interacted with, etc.  The hand or tool moves as normal, but nothing happens.  On BTPR BetaL from ATLauncher.

**Comment by Landrash** [comment]
This happens to me at time and it's generally after I tabbed out of the game and it's pretty common in Minecraft on all versions I've tried.

Quick fix for me is in general to hit *ESC*, tab out and in and continue on as usual.
Google it and you'll find plentiful of folks having the same problem as you with Minecraft in general.

**Comment by otakucode** [comment]
Actually, I've figured it out a bit more precisely.  It's not just that right-click ceases to work, and it doesn't cease forever.  It's like lag.  If I come back and break a few blocks, I will not be able to pick them up, then several seconds later (at least 30, maybe a minute, I will try to time it sometime) I will glitch back into a prior position and be able to pick up the blocks and everything will continue as normal.  It's as if I were playing on a remote server rather than locally in single player.  

It's definitely not normal behavior on my system, I just finished playing the Blightfall modpack for 2-3 months which has a similar number of mods (though different ones) and I never encountered this.  The way I normally play is to basically leave Minecraft running all the time, just pausing and going to do work and coming back to it hours later.  I'm running a Linux Mint 17.2 system on an i7 processor with 32GB of RAM, ATLauncher is running from my home directory on a 512GB Samsung SSD.  I really don't think I should be having any performance problems with this setup... I never encounter any degree of de-sync between the local server process and my client except when pausing and returning to it, and I only get this on this modpack.  It's very strange.  If the game were open to LAN or something I could see the client doing some catching-up upon my return, but it's not, so everything pauses when I pause.  It just seems to take the internal server process a bit to wake up.  I don't see anything happening in the ATLauncher console.  

I'm a developer myself so if there's anything you'd like me to test, just let me know.  I know how annoying figuring out an issue like this can be, some random machine is having inconsistent performance.  Perhaps there is a particular mod that you might guess to be the culprit?  Most of the mods in this pack are new to me, so I'm not familiar with hardly any of them, certainly not enough to guess which might be crunching hard on resume from a pause.

**Comment by Landrash** [comment]
@otakucode Oh, someone that writes proper documentation of the error they are having! =)
I have just about the same setup that your using with the exception of using Arch instead of Mint. I've had the same problem as you and just assumed that was the error I described above or the server I'm playing on lagging behind.

I'm not affiliated with the modpack team but since I'm having the same problem I'm going to try to replicate your problem and see if I can figure it out. 
Only thing I can think of right now would be to check log for the server lagging behind and to run the mc instance trough a profiler.

**Comment by b0bst3r** [comment]
I test the builds for sometimes hours at a time usually in SSP and have never come across this at all. Unless I can replicate it I can't see how I can help.

**Comment by Watschman** [comment]
Minecraft runs all the time on a server for quite a while now. The only difference to multiplayer is, that you are running a Singleplayer world with an integrated server instead of a dedicated server. I can not say what is causing this problem but if you are able to check the usuage of every single core on your CPU. It might be worth a try to look on the usuage of the core which is used by minecraft(because 90% of the game is only Singlecore) after returning to the game. It never happened like this on my side when I play SSP, so this is only a guess. Most tps issues (at least your problem sounds like a tps issue) are caused by high CPU usuage or network issues(which shouldn't matter since you are on SSP)

**Comment by Landrash** [comment]
@Watschman @b0bst3r I'm aware of the problem and it's a bit like looking for a needle in a stack of needles. Since the problem is fairly undefined and it doesn't really cause more than an annoyance it might be on of those things that wont get fixed and we all have to be ok with it.

I tried replicating it yesterday and I'm only partly able to do it on one system and the common denominator it has with @otakucode is that it's running on Linux.

**Comment by otakucode** [comment]
Well, I don't know what changed, but Beta O fixed this issue completely for me.  Since updating, there is zero lag in opening inventories, breaking blocks, etc even after 12+ hours of remaining paused.  I was really mystified by this bug, since in single player it simply made no sense... there are no block updates or ticks to process when coming back from being paused.  And yet the delay grew with the length of time the game had been paused for.  I had no hope of seeing this issue fixed and had resigned to simply live with it.  When I saw that BTPR wouldn't be likely to see any more updates, I was sure I was stuck with just being patient.  But then today, I returned to the game after having it paused for pretty much the whole day, and it worked flawlessly and immediately.  Huzzah!

Unless someone else is still being affected by this problem, I would vote to close this issue as no longer a problem!
