### ISSUE TITLE
Fatal Error, Connection Terminated: NuclearCraft Entity 28 failed to spawn

### ISSUE THREAD

**Issue by ChronomegaIV** [BevoTechPack/BevoTechPack#980]
Seems to happen mostly around my house in game. If I remove my playerdata and go back to original spawn, I can play for a few minutes and then the issue returns. 

Pastebin: http://paste.atlauncher.com/view/6f120244

It's pretty far down the list. Starts at 198. [05/5/2016 19:59:46 PM]

**Comment by b0bst3r** [comment]
This on a server?

**Comment by ChronomegaIV** [comment]
Yes. It's a locally hosted server on another computer in my home. It started as a Bevos version N and we have updated it each time (along with the clients to match). We would copy the world save folder along with the server.properties, launchserver.bat and eula.txt. Attached is the server log that matches the same time period as the client log.

I have temporarily fixed the issue by disabling Nuclearcraft monster spawn.

[fml-server-3.txt](https://github.com/BevoTechPack/BevoTechPack/files/252681/fml-server-3.txt)

**Comment by b0bst3r** [comment]
Ok, re-enable the nuclear monster on the server and then copy all the configs from server to client.  This is caused by configs not matching on server/client, we had this happen disabling ender Zoos dirt mob on server and client not having it disabled.  It's nothing to do with Nuclearcraft, and if you don't sync configs other crashes will start happening, trust me we've been there and experienced this.

**Comment by ChronomegaIV** [comment]
I'll give it a try and let you know. Just finished copying all of the finalized configs from the server and will be launching shortly.

**Comment by ChronomegaIV** [comment]
About an hour has gone by with no crashes. Thanks for the help!
